#!/usr/bin/env python3
"""Wire this repo into Claude Code (statusline + hooks), or unwire it.
Works on macOS, Linux and Windows.

    python3 setup_claude.py install     (Windows: py setup_claude.py install)
    python3 setup_claude.py uninstall

install:
  - backs up ~/.claude/settings.json (and your statusline script, if any)
  - appends state-reporting hook commands alongside whatever hooks you
    already have (nothing is replaced); commands invoke report.py with
    the running Python interpreter, so no python-vs-python3 issues
  - forwards the statusline payload to the daemon via a small Python
    wrapper — your original statusline command (if any) still renders
    your status bar

uninstall reverses both. Re-running install is a no-op if already wired.
"""

from __future__ import annotations

import json
import pathlib
import shutil
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
CLAUDE_DIR = pathlib.Path.home() / ".claude"
SETTINGS = CLAUDE_DIR / "settings.json"
WRAPPER = CLAUDE_DIR / "busybar-statusline.py"
PY = sys.executable

HOOK_STATES = {
    "SessionStart": "IDLE",
    "SessionEnd": "ENDED",
    "UserPromptSubmit": "THINKING",
    "PreToolUse": "WORKING",
    "PostToolUse": "WORKING",
    "PostToolUseFailure": "ERROR",
    "PermissionRequest": "WAIT",
    "PermissionDenied": "ERROR",
    "Elicitation": "WAIT",
    "StopFailure": "FAILED",
    "Stop": "COMPLETE",
}

MARKER = "# busybar-claude-status forwarder"

WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
{marker}
# Generated by setup_claude.py - forwards the statusline payload to the
# busybar daemon, then renders your status bar (original command below,
# or a minimal fallback).
import json, subprocess, sys
sys.path.insert(0, {repo!r})
import report

ORIGINAL = {original!r}

data = sys.stdin.buffer.read()
report.ensure_daemon()
report.forward("/statusline", data or b"{{}}")
if ORIGINAL:
    sys.exit(subprocess.run(ORIGINAL, shell=True, input=data).returncode)
model = ((json.loads(data or b"{{}}").get("model") or {{}}).get("display_name")) or "Claude"
print(f"[{{model}}]")
'''


def hook_cmd(state: str) -> str:
    return f'"{PY}" "{HERE / "report.py"}" state {state}'


def backup(path: pathlib.Path):
    if path.exists():
        dest = path.with_name(path.name + ".backup-busybar-" + time.strftime("%Y%m%d%H%M%S"))
        shutil.copy2(path, dest)
        print(f"backup: {dest}")


def load_settings() -> dict:
    return json.loads(SETTINGS.read_text()) if SETTINGS.exists() else {}


def save_settings(cfg: dict):
    SETTINGS.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS.write_text(json.dumps(cfg, indent=2, ensure_ascii=False) + "\n")


def _is_ours(command: str) -> bool:
    return str(HERE) in command or "busybar-statusline" in command


def install():
    cfg = load_settings()
    backup(SETTINGS)

    # 1. hooks (append alongside existing ones)
    hooks = cfg.setdefault("hooks", {})
    added = 0
    for event, state in HOOK_STATES.items():
        groups = hooks.setdefault(event, [{"hooks": []}])
        if any(_is_ours(h.get("command", "")) for g in groups for h in g.get("hooks", [])):
            continue
        groups[0].setdefault("hooks", []).append(
            {"type": "command", "command": hook_cmd(state)})
        added += 1
    print(f"hooks: {added} command(s) added")

    # 2. statusline forwarding
    sl = cfg.get("statusLine") or {}
    original = sl.get("command", "")
    if _is_ours(original):
        print("statusline: already forwarding")
    else:
        # If the existing command is a plain bash script we can edit in
        # place (POSIX installs), append the forward line there; in every
        # other case wrap the whole command with the Python wrapper.
        target = pathlib.Path(original.split()[-1]).expanduser() if original else None
        if (sys.platform != "win32" and target and target.is_file()
                and target.suffix == ".sh" and "input=$(cat)" in target.read_text()):
            backup(target)
            target.write_text(target.read_text().replace(
                "input=$(cat)",
                "input=$(cat)\n"
                f"{MARKER}\n"
                f"( printf '%s' \"$input\" | \"{PY}\" \"{HERE / 'report.py'}\""
                " statusline >/dev/null 2>&1 & )",
                1,
            ))
            print(f"statusline: forward line added to {target}")
        else:
            WRAPPER.write_text(WRAPPER_TEMPLATE.format(
                marker=MARKER, repo=str(HERE), original=original))
            try:
                WRAPPER.chmod(0o755)
            except OSError:
                pass
            cfg["statusLine"] = {"type": "command", "command": f'"{PY}" "{WRAPPER}"'}
            if original:
                cfg["statusLine"]["_busybar_original"] = original
            print(f"statusline: wrapper installed at {WRAPPER}")

    save_settings(cfg)
    print("done — restart your Claude Code sessions to pick up the hooks.")


def uninstall():
    cfg = load_settings()
    backup(SETTINGS)

    removed = 0
    for groups in (cfg.get("hooks") or {}).values():
        for g in groups:
            before = len(g.get("hooks", []))
            g["hooks"] = [h for h in g.get("hooks", [])
                          if not _is_ours(h.get("command", ""))]
            removed += before - len(g["hooks"])
    print(f"hooks: {removed} command(s) removed")

    sl = cfg.get("statusLine") or {}
    if "busybar-statusline" in sl.get("command", ""):
        original = sl.get("_busybar_original")
        cfg["statusLine"] = ({"type": "command", "command": original}
                             if original else None)
        if cfg["statusLine"] is None:
            cfg.pop("statusLine", None)
        WRAPPER.unlink(missing_ok=True)
        print("statusline: wrapper removed")
    else:
        target = pathlib.Path((sl.get("command", "").split() or [""])[-1]).expanduser()
        if target.is_file() and MARKER in target.read_text():
            lines = target.read_text().splitlines(keepends=True)
            out, skip = [], 0
            for line in lines:
                if MARKER in line:
                    skip = 2  # marker + forward line
                if skip:
                    skip -= 1
                    continue
                out.append(line)
            backup(target)
            target.write_text("".join(out))
            print(f"statusline: forward line removed from {target}")

    save_settings(cfg)
    print("done.")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "install":
        install()
    elif cmd == "uninstall":
        uninstall()
    else:
        sys.exit(__doc__)
